name: Update Linear Issues

on:
  push:
    branches:
      - release/dev

jobs:
  update-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run update script
        env:
          LINEAR_API_TOKEN: ${{ secrets.LINEAR_API_TOKEN }}
        run: cat ${GITHUB_WORKSPACE}/.github/scripts/update_linear_issues.sh
