name: Filter Commits Workflow

on:
  push:
    branches:
      - release/dev

jobs:
  filter-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Fetch commits and filter
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: $LINEAR_API_KEY" \
          --data '{
            "query": "mutation($id: String!, $stateId: String!) { issueUpdate(id: $id, input: { stateId: $stateId }) { success } }",
            "variables": {
              "id": "TES-1",
              "stateId": "7db1c39e-bc7e-4c54-8ba9-eb0511002041"
            }
          }' https://api.linear.app/graphql
